services:
  pgvector:
    container_name: pgdb-store
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=dbCryptoCurrency'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=admin'
    volumes:
      - chatbot_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  chatbot_data: